columnSuffix: null
handle: city
instructions: null
name: City
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:4c9daaa2-fb08-4bef-afdb-ad653f629156' # Locations
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
